site_name: STRATICA
site_description: Stratigraphic Pattern Recognition & Paleoclimatic Temporal Reconstruction
site_author: Samir Baladi
site_url: https://stratica.readthedocs.io

repo_url: https://github.com/gitdeeper8/STRATICA

theme:
  name: material
  palette:
    primary: teal
    accent: deep orange

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Parameters: parameters.md

plugins:
  - search
